print("Nume, Prenume:           Colbasevici Mihai \n")
print("Data și locul nașterii:  18.11.2004, mun. Bălți \n")
print("E-mail:                  colbasevicim@gmail.com \n")
print("Telefon:                 +37367351368 \n")
print("Adresa:                  str. Constantin Stamati 22 \n")
print("Naționalitate:           rusă \n")
print("Studii:                  I.P.L.T 'Mihai Eminescu' (2011 - prezent) \n")
print("Limbi străine:           Limba germană (A2) \n")
print("                         Limba engleză (A2) \n")
print("Alte informații:         Pasionat de calculatoare, programare, matematică, chimie și fizică \n") 